import type { Listing } from "@food-rescue/shared";

export const DUMMY_LISTINGS: (Listing & { merchant_name: string; merchant_address: string })[] = [
  {
    id: "1",
    merchant_id: "m1",
    title: "Surprise Bag — Roti & Pastry",
    description: "Campuran roti, croissant, dan danish pastry sisa hari ini. Masih fresh & layak konsumsi.",
    photo_url: null,
    category: "Bakery",
    is_halal: true,
    original_price: 75000,
    discounted_price: 25000,
    weight_kg: 1.5,
    quantity: 5,
    quantity_sold: 2,
    pickup_start: "2026-09-17T16:00:00",
    pickup_end: "2026-09-17T19:00:00",
    type: "surprise_bag",
    status: "active",
    created_at: "2026-09-17T10:00:00",
    merchant_name: "Bakery Makmur",
    merchant_address: "Jl. Sudirman No. 12, Jakarta Selatan",
  },
  {
    id: "2",
    merchant_id: "m2",
    title: "Nasi Campur Komplit",
    description: "Nasi campur dengan lauk ayam, sayur, dan sambal. Porsi besar, cocok untuk makan siang/malam.",
    photo_url: null,
    category: "Restoran",
    is_halal: true,
    original_price: 35000,
    discounted_price: 15000,
    weight_kg: 0.8,
    quantity: 10,
    quantity_sold: 7,
    pickup_start: "2026-09-17T17:00:00",
    pickup_end: "2026-09-17T20:00:00",
    type: "specific",
    status: "active",
    created_at: "2026-09-17T11:00:00",
    merchant_name: "Warung Bu Sari",
    merchant_address: "Jl. Gatot Subroto No. 45, Jakarta Selatan",
  },
  {
    id: "3",
    merchant_id: "m3",
    title: "Surprise Bag — Sushi & Bento",
    description: "Mix sushi roll, nigiri, dan side dishes. Dibuat hari ini, harus diambil sebelum tutup.",
    photo_url: null,
    category: "Japanese",
    is_halal: false,
    original_price: 120000,
    discounted_price: 40000,
    weight_kg: 1.0,
    quantity: 3,
    quantity_sold: 1,
    pickup_start: "2026-09-17T19:00:00",
    pickup_end: "2026-09-17T21:00:00",
    type: "surprise_bag",
    status: "active",
    created_at: "2026-09-17T12:00:00",
    merchant_name: "Sushi Tei Express",
    merchant_address: "Mall Grand Indonesia, Lt. 3",
  },
  {
    id: "4",
    merchant_id: "m4",
    title: "Aneka Kue Tradisional",
    description: "Lemper, klepon, getuk, dan onde-onde. Dibuat pagi ini, masih segar.",
    photo_url: null,
    category: "Bakery",
    is_halal: true,
    original_price: 50000,
    discounted_price: 18000,
    weight_kg: 1.2,
    quantity: 8,
    quantity_sold: 3,
    pickup_start: "2026-09-17T14:00:00",
    pickup_end: "2026-09-17T17:00:00",
    type: "specific",
    status: "active",
    created_at: "2026-09-17T08:00:00",
    merchant_name: "Dapur Nusantara",
    merchant_address: "Jl. Kemang Raya No. 8, Jakarta Selatan",
  },
  {
    id: "5",
    merchant_id: "m5",
    title: "Salad Bowl + Juice",
    description: "Fresh salad bowl dengan grilled chicken dan cold-pressed juice. Sehat & affordable.",
    photo_url: null,
    category: "Healthy",
    is_halal: true,
    original_price: 65000,
    discounted_price: 25000,
    weight_kg: 0.7,
    quantity: 6,
    quantity_sold: 6,
    pickup_start: "2026-09-17T11:00:00",
    pickup_end: "2026-09-17T14:00:00",
    type: "specific",
    status: "sold_out",
    created_at: "2026-09-17T09:00:00",
    merchant_name: "Green Bowl Co.",
    merchant_address: "Jl. Senopati No. 22, Jakarta Selatan",
  },
  {
    id: "6",
    merchant_id: "m6",
    title: "Surprise Bag — Pizza Slice",
    description: "3-4 slice pizza berbagai topping. Sisa dari lunch rush, masih hangat.",
    photo_url: null,
    category: "Western",
    is_halal: true,
    original_price: 80000,
    discounted_price: 30000,
    weight_kg: 0.9,
    quantity: 4,
    quantity_sold: 0,
    pickup_start: "2026-09-17T18:00:00",
    pickup_end: "2026-09-17T21:00:00",
    type: "surprise_bag",
    status: "active",
    created_at: "2026-09-17T13:00:00",
    merchant_name: "Pizza Place",
    merchant_address: "Jl. Blok M No. 5, Jakarta Selatan",
  },
];
